[package]
name = "nsbm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nsbm"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
ndarray = { version = "0.14.0", features = ["blas", "rayon"] }
ndarray-linalg = "0.13"
ndarray-rand = "0.13.0"
blas-src = { version = "0.8", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }
