[package]
name = "nsbm"
version = "0.1.0"
edition = "2021"
authors = ["Reece Humphreys <reecewh@icloud.com>"]


[lib]
name = "nsbm"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
pyo3 = { version = "0.16.4", features = ["extension-module"] }
